import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'System Architecture',
      link: {
        type: 'doc',
        id: 'system-architecture',
      },
      items: [
        {
          type: 'category',
          label: 'Architectural Evidence',
          link: { 
            type: 'generated-index',
            title: 'Architectural Evidence',
            description: 'Raw decompiled code snippets used as direct evidence for architectural descriptions.'
          },
          items: [
            { type: 'autogenerated', dirName: 'architectural_evidence' },
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Core Concepts',
      link: { type: 'generated-index' },
      items: [
        'concepts/game-concepts',
        'concepts/coordinate-systems',
      ],
    },
    {
      type: 'category',
      label: 'Network Protocols',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'category',
          label: 'Game Server (gs2c/c2gs)',
          link: { type: 'generated-index' },
          items: [
            { type: 'autogenerated', dirName: 'protocols/game' },
          ]
        },
        { type: 'autogenerated', dirName: 'protocols/login' },
        { type: 'autogenerated', dirName: 'protocols/portal' },
        { type: 'autogenerated', dirName: 'protocols/web_api' },
      ]
    },
    {
      type: 'category',
      label: 'Reverse Engineering',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: 'methodologies' },
        { type: 'autogenerated', dirName: 'tooling' },
      ],
    },
    {
      type: 'category',
      label: 'Engine Internals',
      link: { type: 'generated-index' },
      items: [
        'engine_internals/internal-imgui-analysis',
        'engine_internals/reflection_system',
        { type: 'autogenerated', dirName: 'engine_internals/evidence' },
      ],
    },
  ],
};

export default sidebars;