import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    'system-architecture',
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'concepts/game-concepts',
        'concepts/coordinate-systems',
      ],
    },
    {
      type: 'category',
      label: 'Network Protocols',
      link: {
        type: 'doc',
        id: 'protocols/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'protocols',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reverse Engineering',
      items: [
        {
          type: 'autogenerated',
          dirName: 'methodologies',
        },
        {
          type: 'autogenerated',
          dirName: 'tooling',
        },
      ],
    },
    {
      type: 'category',
      label: 'Engine Internals',
      link: {
        type: 'doc',
        id: 'engine_internals/index',
      },
      items: [
        'engine_internals/internal-imgui-analysis',
        'engine_internals/reflection_system',
        {
          type: 'autogenerated',
          dirName: 'engine_internals/evidence',
        },
      ],
    },
    {
      type: 'category',
      label: 'Architectural Evidence',
      link: {
        type: 'doc',
        id: 'architectural_evidence/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'architectural_evidence',
        },
      ],
    },
  ],
};

export default sidebars;
